version: '3'

services:
    nginx:
        container_name: template-nginx
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./.nginx:/etc/nginx/conf.d
            - ./:/var/www/app
            - ./storage/logs/nginx:/var/log/nginx
        networks:
            app-net:
                aliases:
                    - template-app.test
        depends_on:
            - app
        command: [ nginx-debug, '-g', 'daemon off;' ]
    app:
        container_name: template-app
        build: .
        volumes:
            - ./:/var/www/app
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - app-net

networks:
    app-net:
        driver: bridge
