services:
  nginx:
    build:
        context: .
        dockerfile: ./infrastructure/nginx/Dockerfile
        target: development
    volumes:
      - ./public:/var/www/html/public
      - ./storage/logs/nginx:/var/log/nginx
    ports:
      - ${APP_PORT-80}:80
    depends_on:
      - php-fpm
    networks:
      - development

  php-fpm:
    build:
        context: .
        dockerfile: ./infrastructure/php/Dockerfile
        target: development
        args:
          - XDEBUG_ENABLED=${XDEBUG_ENABLED-false}
    volumes:
      - ./:/var/www/html
    networks:
      - development

networks:
  development:
