services:
  nginx:
    build:
        context: .
        dockerfile: ./infrastructure/nginx/Dockerfile
        target: development
    volumes:
      - ./public:/var/www/html/public
      - ./storage/logs/nginx:/var/log/nginx
    ports:
      - ${APP_PORT-80}:80
    depends_on:
      - php-fpm
    networks:
      - development

  php-fpm:
    build:
        context: .
        dockerfile: ./infrastructure/php/Dockerfile
        target: development
        args:
          - XDEBUG_ENABLED=${XDEBUG_ENABLED-false}
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - development

  database:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - ${DB_PORT-3306}:3306
    networks:
      - development
    volumes:
      - './storage/database-data:/var/lib/mysql'
      - './storage/logs/database:/var/log/mysql'
#      - './infrastructure/database/mysql.cnf:/etc/mysql/conf.d/my.cnf' # Uncomment for logging

  node:
    build:
      context: .
      dockerfile: ./infrastructure/node/Dockerfile
      target: base
    working_dir: /var/www/html
    tty: true
    volumes:
      - ./:/var/www/html
    ports:
      - ${VITE_PORT-5173}:5173
    networks:
      - development

networks:
  development:
